// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int iterations = Integer.parseInt(args[0]);

		int countGreaterThanHalf = 0;
		int countLessThanOrEqualToHalf = 0;

		for(int i = 0; i < iterations; i++) {
			Double randomValue = Math.random() * 1;
			if(randomValue < 0.5) {
				countLessThanOrEqualToHalf++;
			}
			else {
				countGreaterThanHalf++;
			}
		}

		System.out.println("> 0.5: " + countGreaterThanHalf + " times");
		System.out.println("<= 0.5: " + countLessThanOrEqualToHalf + " times");
		
		if (!(countLessThanOrEqualToHalf == 0) && !(countGreaterThanHalf == 0)) {
            double ratio;
            if (countGreaterThanHalf > countLessThanOrEqualToHalf) {
                ratio = (double) countLessThanOrEqualToHalf / countGreaterThanHalf;
            } else {
                ratio = (double) countGreaterThanHalf / countLessThanOrEqualToHalf;
            }
            System.out.println("Ratio: " + ratio);
        }
	}
}
